# Generated by Django 3.2.9 on 2021-11-29 22:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be alphanumeric, with no spaces.', regex='^[a-zA-Z0-9_.-]+$')], verbose_name='Username'),
        ),
    ]
