# Generated by Django 3.2.9 on 2021-11-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_dir',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
